###
GET {{$dotenv localhost}}/catalog/
Authorization: Basic admin:
###
GET {{$dotenv localhost}}/catalog/$metadata
Authorization: Basic admin:
###
GET {{$dotenv localhost}}/catalog/SDKgetOrganizations()
Authorization: Basic admin:
###
GET {{$dotenv localhost}}/catalog/getOrganizations()
Authorization: Basic admin:
